### ISSUE TITLE
USB connection fails on Windows 7

### ISSUE THREAD

**Issue by psiemens** [onflow/ledger-app-flow#23]
Several users have reported issues when attempting to connect to their Ledger device through Flow Port.

## Details

- Device specs:
  - Nano S over USB
  - Google Chrome
  - Windows 7 64-bit
- User reports being able to use the same Nano S device in MetaMask
- Disabling MetaMask does not fix the problem
- Closing Ledger Live does not fix the problem

## Reproduction Steps

1. Navigate to the Flow Port login page and select Ledger
2. After Ledger popup opens, click "Connect"
3. Chrome should display the USB device dropdown
4. "Nano S" appears briefly in the dropdown but then disappears from the list, showing "No compatible devices"
5. Close the dropdown by clicking outside of the dropdown. The page should say "Sorry, we couldn't connect to your Ledger."

- [x] I was able to reproduce on a Windows 7 64-bit machine with both Nano S and X

**Comment by psiemens** [comment]
I was able to reproduce this error on a Windows 7 machine. 

The Port is configured to use Web USB to communicate with the Ledger. The official package notes known issues when connecting on Windows: https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-transport-webusb#support-status

The page links to [this issue](https://github.com/WICG/webusb/issues/143), which describes a known driver issue on Windows that can be potentially fixed using the [Zadig](https://zadig.akeo.ie/) tool to install missing drivers. I tried the tool but wasn't able to fix the problem.

**Comment by psiemens** [comment]
I looked at the MetaMask source code and found that it uses the (now legacy) U2F library to interface with Ledger devices. The [U2F transport library](https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-transport-u2f) appears to interchangeable with the current USB transport. I'm going to try swapping them out and seeing if that fixes this problem while still maintaining functionality on other systems.

**Comment by psiemens** [comment]
U2F support must be enabled in the Ledger app itself. I was able to enable it on my development device and confirmed that U2F transport works on Windows 7. However, we'd like to avoid enabling U2F if possible due to the fact that it is now a deprecated, unstable API.

**Comment by jleni** [comment]
I strongly recommend avoiding U2F, it is not just deprecated. Ledger and us intentionally dropped support because of a large number of problems that it brings. Several other projects we support had a lot of trouble because of U2F suddenly breaking on Windows 10 May update, browser updates, etc. U2F was not designed for this purpose and it is there because if was the only alternative many years ago.

**Comment by jleni** [comment]
Last but not least, Windows 7 reached end of life too. Microsoft provides an upgrade path if necessary. Also, I would not recommend using a computer with an OS that does not receive security updates if you are dealing with cryptocurrencies.

**Comment by caseyturnerarrington** [comment]
Closing this as we are not going to do any additional effort here.
