### ISSUE TITLE
Authorizer out-of-bounds write

### ISSUE THREAD

**Issue by psiemens** [onflow/ledger-app-flow#8]
The following bug was discovered by fuzzing:

> https://github.com/LedgerHQ/app-flow/blob/master/app/src/parser_impl.c#L429
>
> In this line, `v->authorizer_count` is not checked to be within bounds of `v->authorizer[]` and this leads to an out-of-bounds write when `v->ctx.bufferLen` is larger than `v->authorizer[]`.

## Definition of Done

- [x] Add a test case that reproduces this bug
- [x] Patch the implementation of `parser_impl.c` to fix this bug

**Comment by jleni** [comment]
When you run the fuzzer, the test input to reproduce the problem is stored.

https://github.com/onflow/ledger-app-flow/blob/master/fuzz/run-fuzz-crashes.py

Later can run all known crashes to verify fixes

**Comment by jleni** [comment]
https://github.com/LedgerHQ/app-flow/blob/e382b9ca8746eb56ef3d6d628bc44a4e08bbd844/app/src/parser_impl.c#L428

https://github.com/LedgerHQ/app-flow/blob/e382b9ca8746eb56ef3d6d628bc44a4e08bbd844/app/src/parser_impl.c#L428-L431

can change to
```
  while (v->ctx.offset < v->ctx.bufferLen) {
        CHECK_PARSER_ERR(_readProposalAuthorizer(&v->ctx, &v->authorizer[v->authorizer_count]))
        v->authorizer_count++;
        if (v->authorizer_count >= 16) {
           return parser_unexpected_number_items;
        }
    }
```

**Comment by psiemens** [comment]
Thanks @jleni!

**Comment by psiemens** [comment]
Closed by https://github.com/LedgerHQ/app-flow/pull/4
